apiVersion: v1
kind: Pod
metadata:
  name: debian
  labels:
    name: debian
    dept: voiceai
spec:
  containers:
    - name: debian-container
      image: debian
      command: ["/bin/sh"]
      args: ["-c", "echo hello debian && sleep 3600"]
