apiVersion: v1
kind: Pod
metadata:
  name: nodejs-echo-pod-configmap
spec:
  containers:
    - name: nodejs-container
      image: node:14
      envFrom:
        - configMapRef:
            name: my-config
      command: ["node"]
      args: ["-e", "console.log(process.env.MY_ENV_VARIABLE)"]
