apiVersion: v1
kind: Pod
metadata:
  name: nodejs-echo-pod
spec:
  containers:
    - name: nodejs-container
      image: node:14 # You can specify the Node.js version you prefer
      env:
        - name: MY_ENV_VARIABLE
          value: "Hello, World!" # Replace this with your desired environment variable value
      command: ["node"]
      args: ["-e", "console.log(process.env.MY_ENV_VARIABLE)"]
